const {onCall,HttpsError}=require("firebase-functions/v2/https");
const {initializeApp}=require("firebase-admin/app");
const {getAuth}=require("firebase-admin/auth");
const {getFirestore,FieldValue,Timestamp}=require("firebase-admin/firestore");
const {defineSecret}=require("firebase-functions/params");
const crypto=require("crypto"),{promisify}=require("util");
initializeApp();
const db=getFirestore(),scrypt=promisify(crypto.scrypt),TWOFACTOR_API_KEY=defineSecret("TWOFACTOR_API_KEY");
const REGION="asia-south1",SESSION_MS=36000000,OTP_MS=300000,ALL_TABS=["dashboard","reports","leads","freshleads","team","security"];
const mobile10=x=>String(x||"").replace(/\D/g,"").slice(-10),hash=x=>crypto.createHash("sha256").update(String(x)).digest("hex"),text=(x,n=120)=>String(x||"").replace(/[<>]/g,"").trim().slice(0,n),tabs=x=>Array.isArray(x)?[...new Set(x.filter(t=>ALL_TABS.includes(t)))].slice(0,20):[];
const ipOf=r=>String(r.rawRequest?.headers?.["x-forwarded-for"]||r.rawRequest?.ip||"Unavailable").split(",")[0].trim();
const locationOf=r=>{const h=r.rawRequest?.headers||{};return[h["x-appengine-city"],h["x-appengine-region"],h["x-appengine-country"]].filter(Boolean).map(x=>text(x,60)).join(", ")||"Location unavailable";};
const deviceOf=r=>({label:text(r.data?.device?.label||"Unknown device",100),browser:text(r.data?.device?.browser||"Unknown browser",60),os:text(r.data?.device?.os||"Unknown OS",60),language:text(r.data?.device?.language||"",20),timezone:text(r.data?.device?.timezone||"",60),userAgent:text(r.rawRequest?.headers?.["user-agent"]||"",300)});
const strong=p=>typeof p==="string"&&p.length>=8&&p.length<=12&&/[a-z]/.test(p)&&/[A-Z]/.test(p)&&/\d/.test(p)&&/[^A-Za-z0-9]/.test(p);
async function limit(bucket,key,max,ms){const ref=db.collection("_panelLoginLimits").doc(hash(`${bucket}:${key}`));await db.runTransaction(async tx=>{const s=await tx.get(ref),now=Date.now(),d=s.exists?s.data():{},same=now-Number(d.windowStart||0)<ms,count=same?Number(d.count||0):0;if(count>=max)throw new HttpsError("resource-exhausted","Too many attempts. Try again later.");tx.set(ref,{bucket,count:count+1,windowStart:same?d.windowStart:now,expiresAt:Timestamp.fromMillis(now+ms)});});}
async function ownerFor(mobile){const s=await db.collection("mteam").where("mobile","==",mobile).limit(2).get(),o=s.docs.find(d=>d.data().active===true);if(!o)throw new HttpsError("permission-denied","Not authorised.");return o;}
async function teamFor(owner){let changed=false;const team=(Array.isArray(owner.data().team)?owner.data().team:[]).map(u=>{const{password,pin,...safe}=u||{};if(password!==undefined||pin!==undefined||!safe.id)changed=true;return{...safe,id:safe.id||crypto.randomUUID()};});if(changed)await owner.ref.update({team,updatedAt:FieldValue.serverTimestamp()});return team;}
async function actorsFor(owner){const team=await teamFor(owner),actors=[{id:owner.id,name:owner.data().name||"Marketing Member",actorType:"owner"},...team.filter(u=>u.active!==false).map(u=>({id:u.id,name:u.name||"Sub-user",actorType:"subuser"}))],creds=await Promise.all(actors.map(a=>db.collection("_panelCredentials").doc(hash(`marketing:${owner.id}:${a.id}`)).get()));return actors.map((a,i)=>({...a,passwordConfigured:creds[i].exists}));}
async function actorFor(owner,id){if(id===owner.id)return{id:owner.id,name:owner.data().name||"Marketing Member",mobile:mobile10(owner.data().mobile),actorType:"owner",tabs:ALL_TABS};const team=await teamFor(owner),u=team.find(x=>x.id===id&&x.active!==false);if(!u)throw new HttpsError("permission-denied","Actor not authorised.");return{...u,actorType:"subuser"};}
async function sendOtp(mobile,otp){const key=TWOFACTOR_API_KEY.value();if(!key)throw new HttpsError("failed-precondition","OTP service is not configured.");try{const r=await fetch(`https://2factor.in/API/V1/${encodeURIComponent(key)}/SMS/+91${mobile}/${otp}/OTP`,{signal:AbortSignal.timeout(10000)}),b=await r.json();if(!r.ok||b?.Status!=="Success")throw new Error("send");}catch(_){throw new HttpsError("unavailable","OTP could not be sent right now.");}}
async function newChallenge(mobile,ownerId){const otp=crypto.randomInt(1000,10000).toString(),salt=crypto.randomBytes(16).toString("hex"),id=crypto.randomBytes(24).toString("hex");await sendOtp(mobile,otp);await db.collection("_panelOtpChallenges").doc(id).set({panel:"marketing",mobile,ownerId,salt,otpHash:hash(`${salt}:${otp}`),attempts:0,verified:false,used:false,createdAt:FieldValue.serverTimestamp(),expiresAt:Timestamp.fromMillis(Date.now()+OTP_MS)});return id;}
async function verifyChallenge(id,otp){const ref=db.collection("_panelOtpChallenges").doc(id),s=await ref.get();if(!s.exists)throw new HttpsError("unauthenticated","OTP session expired.");const d=s.data();if(d.panel!=="marketing"||d.used||d.expiresAt.toMillis()<Date.now()){await ref.delete();throw new HttpsError("unauthenticated","OTP session expired.");}if(Number(d.attempts||0)>=5){await ref.delete();throw new HttpsError("resource-exhausted","Too many incorrect attempts.");}if(hash(`${d.salt}:${otp}`)!==d.otpHash){await ref.update({attempts:FieldValue.increment(1)});throw new HttpsError("unauthenticated","Incorrect OTP.");}const ticket=crypto.randomBytes(32).toString("hex");await ref.update({verified:true,ticketHash:hash(ticket),ticketExpiresAt:Timestamp.fromMillis(Date.now()+OTP_MS),otpHash:FieldValue.delete(),salt:FieldValue.delete()});return{...d,ticket};}
async function readTicket(id,ticket){const ref=db.collection("_panelOtpChallenges").doc(id),s=await ref.get();if(!s.exists)throw new HttpsError("unauthenticated","Login session expired.");const d=s.data();if(d.panel!=="marketing"||!d.verified||d.used||d.ticketExpiresAt.toMillis()<Date.now()||d.ticketHash!==hash(ticket))throw new HttpsError("unauthenticated","Login session expired.");return{ref,data:d};}
async function pHash(p,salt){return(await scrypt(p,salt,64)).toString("hex");}
async function verifyPassword(ownerId,actorId,password,create){if(!strong(password))throw new HttpsError("invalid-argument","Password must be 8–12 characters with uppercase, lowercase, number and special character.");const ref=db.collection("_panelCredentials").doc(hash(`marketing:${ownerId}:${actorId}`)),s=await ref.get();if(!s.exists){if(!create)throw new HttpsError("failed-precondition","Set password using OTP login first.");const salt=crypto.randomBytes(24).toString("hex");await ref.create({panel:"marketing",ownerId,actorId,salt,passwordHash:await pHash(password,salt),createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});return;}const d=s.data(),actual=await pHash(password,d.salt),a=Buffer.from(actual,"hex"),b=Buffer.from(String(d.passwordHash||""),"hex");if(a.length!==b.length||!crypto.timingSafeEqual(a,b))throw new HttpsError("unauthenticated","Incorrect password.");}
function publicSession(doc){const d=doc.data();return{id:doc.id,actorId:d.actorId,actorName:d.actorName,actorType:d.actorType,ip:d.ip,location:d.location,device:d.device,createdAt:d.createdAt?.toMillis?.()||null,lastSeenAt:d.lastSeenAt?.toMillis?.()||null,expiresAt:d.expiresAt?.toMillis?.()||null,revoked:d.revoked===true};}
async function sessionFor(r){if(r.auth?.token?.panel!=="marketing")throw new HttpsError("unauthenticated","Sign in required.");const ref=db.collection("_panelSessions").doc(r.auth.uid),s=await ref.get();if(!s.exists||s.data().panel!=="marketing"||s.data().revoked===true||s.data().expiresAt.toMillis()<=Date.now())throw new HttpsError("unauthenticated","Session expired.");return{ref,data:s.data()};}

exports.marketingStartTwoFactorOtp=onCall({region:REGION,cors:true,secrets:[TWOFACTOR_API_KEY]},async r=>{const m=mobile10(r.data?.mobile);if(!/^\d{10}$/.test(m))throw new HttpsError("invalid-argument","Invalid mobile number.");await Promise.all([limit("marketing_otp_mobile",m,3,600000),limit("marketing_otp_ip",ipOf(r),8,600000)]);const o=await ownerFor(m);return{challengeId:await newChallenge(m,o.id)};});
exports.marketingVerifyTwoFactorOtp=onCall({region:REGION,cors:true},async r=>{const id=String(r.data?.challengeId||""),otp=String(r.data?.otp||"");if(!/^[a-f0-9]{48}$/.test(id)||!/^\d{4}$/.test(otp))throw new HttpsError("invalid-argument","Enter a valid OTP.");await limit("marketing_verify_ip",ipOf(r),20,600000);const v=await verifyChallenge(id,otp),o=await ownerFor(v.mobile);return{loginTicket:v.ticket,actors:await actorsFor(o)};});
exports.marketingCreateSessionFromTwoFactor=onCall({region:REGION,cors:true},async r=>{const challengeId=String(r.data?.challengeId||""),ticket=String(r.data?.loginTicket||""),actorId=String(r.data?.actorId||""),password=String(r.data?.password||"");await limit("marketing_password_ip",ipOf(r),20,600000);const{ref:challengeRef,data:v}=await readTicket(challengeId,ticket),o=await ownerFor(v.mobile),a=await actorFor(o,actorId);await verifyPassword(o.id,a.id,password,true);await challengeRef.update({used:true,ticketHash:FieldValue.delete()});const claims={panel:"marketing",actorType:a.actorType,mteamId:o.id,subUserId:a.actorType==="subuser"?a.id:"",name:text(a.name||"Member",80),mobile:mobile10(a.mobile||v.mobile),parentMobile:v.mobile,tabs:a.actorType==="owner"?ALL_TABS:tabs(a.tabs)},uid=`panel_${hash(`marketing:${o.id}:${a.id}:${crypto.randomBytes(24).toString("hex")}`).slice(0,48)}`,prior=await db.collection("_panelSessions").where("ownerId","==",o.id).get(),previous=prior.docs.map(publicSession).filter(s=>s.actorId===a.id).sort((x,y)=>(y.createdAt||0)-(x.createdAt||0))[0]||null,now=Timestamp.now(),expiresAt=Timestamp.fromMillis(Date.now()+SESSION_MS);await db.collection("_panelSessions").doc(uid).set({panel:"marketing",ownerId:o.id,actorId:a.id,actorName:claims.name,actorType:a.actorType,ip:ipOf(r),location:locationOf(r),device:deviceOf(r),createdAt:now,lastSeenAt:now,expiresAt,revoked:false});return{token:await getAuth().createCustomToken(uid,claims),expiresAt:expiresAt.toMillis(),loginAlert:previous};});
exports.marketingSessionStatus=onCall({region:REGION,cors:true},async r=>{const{ref,data}=await sessionFor(r);await ref.update({lastSeenAt:FieldValue.serverTimestamp()});return{valid:true,expiresAt:data.expiresAt.toMillis()};});
exports.marketingUnlockSession=onCall({region:REGION,cors:true},async r=>{const{ref,data}=await sessionFor(r);await limit("marketing_unlock",`${r.auth.uid}:${ipOf(r)}`,10,900000);await verifyPassword(data.ownerId,data.actorId,String(r.data?.password||""),false);await ref.update({lastSeenAt:FieldValue.serverTimestamp(),lastUnlockAt:FieldValue.serverTimestamp()});return{ok:true};});
exports.marketingListSessions=onCall({region:REGION,cors:true},async r=>{const{data}=await sessionFor(r),s=await db.collection("_panelSessions").where("ownerId","==",data.ownerId).get(),all=r.auth.token.actorType==="owner";return{currentSessionId:r.auth.uid,sessions:s.docs.map(publicSession).filter(x=>all||x.actorId===data.actorId).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)).slice(0,100)};});
exports.marketingRevokeSession=onCall({region:REGION,cors:true},async r=>{const{data}=await sessionFor(r),id=String(r.data?.sessionId||""),target=await db.collection("_panelSessions").doc(id).get();if(!target.exists||target.data().ownerId!==data.ownerId||(r.auth.token.actorType!=="owner"&&target.data().actorId!==data.actorId))throw new HttpsError("permission-denied","Not authorised.");await target.ref.update({revoked:true,revokedAt:FieldValue.serverTimestamp(),expiresAt:Timestamp.fromMillis(0)});try{await getAuth().revokeRefreshTokens(id);}catch(_){}return{ok:true,current:id===r.auth.uid};});
exports.marketingPanelLogout=onCall({region:REGION,cors:true},async r=>{if(!r.auth?.uid)throw new HttpsError("unauthenticated","Not signed in.");await db.collection("_panelSessions").doc(r.auth.uid).delete();try{await getAuth().revokeRefreshTokens(r.auth.uid);}catch(_){}return{ok:true};});
exports.marketingGetProfiles=onCall({region:REGION,cors:true},async r=>{await sessionFor(r);const c=r.auth.token,o=await db.collection("mteam").doc(c.mteamId).get();if(!o.exists||o.data().active!==true)throw new HttpsError("permission-denied","Inactive.");if(c.actorType==="subuser"&&!((o.data().team||[]).some(u=>u.id===c.subUserId&&u.active!==false)))throw new HttpsError("permission-denied","Inactive.");const requested=[...new Set((r.data?.mobiles||[]).map(mobile10).filter(x=>/^\d{10}$/.test(x)))].slice(0,100),users=await db.collection("users").where("referredByMteam","==",c.mteamId).get(),allowed=new Set(users.docs.map(d=>mobile10(d.data().mobileNo))),mobiles=requested.filter(m=>allowed.has(m)),profiles=[];for(let i=0;i<mobiles.length;i+=30){const s=await db.collection("mlmprofiles").where("mobile","in",mobiles.slice(i,i+30)).get();for(const d of s.docs)profiles.push({id:d.id,...d.data()});}return{profiles};});
